

---
plugin: aws_ec2
regions:
  - us-east-1

filters:
  "tag:env": "sonarqube"
  "tag:Name": "private-server*"

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address

keyed_groups:
  - key: tags.env
  - key: tags.az
  - key: tags.Name

strict: False

##ansible-playbook -i aws_ec2.yml play.yaml -l env_sonarqube